//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pills_reminder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PillsReminderEntities : DbContext
    {
        public PillsReminderEntities()
            : base("name=PillsReminderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<IntakeDuration> IntakeDurations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WeekIntake> WeekIntakes { get; set; }
    }
}
